channels:
  - conda-forge
  - rlehe
dependencies:
  - python
  - numpy
  - numba
  - h5py
  - scipy
  - gcc
  - pyfftw
  - mpi4py
  - nano
  - ghostscript
  - openpmd_viewer
  - pip:
    - Forthon
    - python-dateutil
    - fbpic
